/* OpenAWE - A reimplementation of Remedys Alan Wake Engine
 *
 * OpenAWE is the legal property of its developers, whose names
 * can be found in the AUTHORS file distributed with this source
 * distribution.
 *
 * OpenAWE is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * OpenAWE is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenAWE. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef OPENAWE_LIPSUM_H
#define OPENAWE_LIPSUM_H

// Generated by https://www.lipsum.com/
static const char* kLipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec urna ex. Duis eu "
							 "facilisis ipsum. Phasellus ultricies et enim vitae scelerisque. Maecenas faucibus sem "
							 "nec neque fermentum pretium. Sed sed aliquam ligula, at tincidunt velit. Curabitur sit "
							 "amet tellus sed arcu varius egestas. Vivamus eu mi nec leo accumsan consectetur sit amet "
							 "a arcu. Vivamus auctor dui a ex sodales, vitae sagittis elit euismod. Sed posuere luctus "
							 "rutrum. Morbi nunc nisl, faucibus sed varius ut, volutpat vel turpis. Phasellus "
							 "dignissim, purus id pretium mattis, purus ante auctor metus, sit amet ornare dolor diam "
							 "sit amet metus. Donec hendrerit venenatis enim, nec cursus nibh pharetra et.\n"
							 "\n"
							 "Cras tortor lacus, vestibulum eget dapibus tempus, vestibulum ut dui. Ut enim felis, "
							 "pharetra vitae hendrerit sit amet, bibendum ac tellus. Integer lacinia augue ante, in "
							 "volutpat sem luctus ut. Sed cursus fermentum vulputate. Nulla mollis pulvinar maximus. "
							 "Curabitur cursus ligula at congue fermentum. Proin gravida tellus non massa posuere "
							 "mattis quis id nisi. Duis ut vulputate quam. Curabitur ultrices arcu faucibus, "
							 "ullamcorper neque nec, mattis magna. Morbi commodo maximus eros in pharetra. Proin "
							 "elementum nisi non mi suscipit, nec molestie nunc aliquet. In facilisis nisl id erat "
							 "suscipit aliquam. Integer tempor venenatis velit id vehicula. In sagittis accumsan "
							 "pharetra. Vestibulum volutpat nisi in sem tristique, elementum tempus erat eleifend.\n"
							 "\n"
							 "Maecenas porta erat lectus, sit amet aliquam ante commodo pharetra. Nunc venenatis "
							 "tempor ex, eget venenatis urna iaculis vitae. Morbi suscipit purus nec erat pharetra "
							 "tincidunt. Nunc lectus dui, molestie et urna vitae, laoreet elementum nisi. Vestibulum "
							 "viverra porttitor lacus sed elementum. Etiam feugiat ornare luctus. Mauris in dui "
							 "facilisis, bibendum odio mollis, gravida quam. Proin vehicula non turpis nec dapibus. "
							 "Fusce nisl erat, sagittis non nisi eget, condimentum blandit nisi.\n"
							 "\n"
							 "Quisque blandit velit sed tempor ultrices. Proin at posuere quam. Suspendisse varius "
							 "justo magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur porta "
							 "nec turpis non vulputate. Suspendisse potenti. Vivamus vitae sollicitudin metus. "
							 "Curabitur non neque nibh.\n"
							 "\n"
							 "Sed non rhoncus nisi. Aenean sed mauris eleifend, commodo sem et, aliquet velit. Sed "
							 "posuere posuere purus, nec finibus nunc gravida a. Morbi id ligula lorem. Phasellus sit "
							 "amet tortor in mauris luctus porta vel a nulla. Donec ultrices nibh sit amet "
							 "urna malesuada, in fermentum nisi tincidunt. Praesent fringilla euismod ipsum, quis "
							 "lobortis velit tristique ut. Proin ac est in nunc gravida molestie. Ut non eros libero. "
							 "Ut auctor at justo a dignissim. In in venenatis nulla. Quisque ut fringilla massa, "
							 "maximus facilisis dui. Morbi et convallis tortor. Morbi ut odio non est consectetur "
							 "fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur "
							 "ridiculus mus. Mauris lacinia dapibus pharetra. \n";

#endif //OPENAWE_LIPSUM_H
