/* OpenAWE - A reimplementation of Remedys Alan Wake Engine
 *
 * OpenAWE is the legal property of its developers, whose names
 * can be found in the AUTHORS file distributed with this source
 * distribution.
 *
 * OpenAWE is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 *
 * OpenAWE is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenAWE. If not, see <http://www.gnu.org/licenses/>.
 */

#include "src/engines/awan/functions.h"

namespace Engines::AlanWakesAmericanNightmare {

const std::map<std::string, Functions::NativeFunction<AlanWakesAmericanNightmare::Functions>> Functions::_functions = {
		{"MODESWITCH.HintNextVideo"                    , {nullptr                             , {kString}}},
		{"MODESWITCH.PlayVideo"                        , {nullptr                             , {kString}}},
		{"MODESWITCH.PlayVideoLooping"                 , {nullptr                             , {kString}}},
		{"MODESWITCH.PlayVideoWithDelay"               , {nullptr                             , {kString, kFloat, kFloat}}},
		{"MODESWITCH.PlayVideoWithDelayCut"            , {nullptr                             , {kString, kFloat, kFloat}}},
		{"MODESWITCH.ActivateMainMenu"                 , {nullptr                             , {kString}}},

		{"GAME.SetTaskComplete"                        , {nullptr                             , {kEntity}}},
		{"GAME.ActivateTask"                           , {&Functions::activateTask            , {kEntity}}},
		{"GAME.SetTaskCompleteDuringNextVideo"         , {nullptr                             , {kEntity}}},
		{"GAME.TeleportPlayerToWaypointDuringNextVideo", {nullptr                             , {kEntity}}},
		{"GAME.StartEpisode"                           , {nullptr                             , {kString}}},
		{"GAME.StartVideoCommentary"                   , {nullptr                             , {kString}}},
		{"GAME.StopVideoCommentary"                    , {nullptr                             , {}}},
		{"GAME.FadeInSounds"                           , {nullptr                             , {kFloat}}},
		{"GAME.FadeOutSounds"                          , {nullptr                             , {kFloat}}},
		{"GAME.EnablePlayerControls"                   , {nullptr                             , {kBool}}},
		{"GAME.SpawnBirds"                             , {nullptr                             , {kInt, kFloat, kFloat, kFloat}}},
		{"GAME.EnableBirds"                            , {nullptr                             , {kBool}}},
		{"GAME.SetSunMoonIntensityMultiplier"          , {nullptr                             , {kFloat, kFloat}}},
		{"GAME.EnableRevealCamera"                     , {nullptr                             , {kBool}}},
		{"GAME.SetTime"                                , {nullptr                             , {kInt, kInt, kFloat}}},
		{"GAME.SetSunYRotation"                        , {nullptr                             , {kFloat}}},
		{"GAME.SetWind"                                , {nullptr                             , {kFloat, kFloat}}},
		{"GAME.PlayMusic"                              , {&Functions::playMusic               , {kEntity}}},
		{"GAME.PlayMusicAt"                            , {nullptr                             , {kEntity, kFloat, kFloat}}},
		{"GAME.FadeInMusic"                            , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.FadeOutMusic"                           , {nullptr                             , {kFloat}}},
		{"GAME.StopMusic"                              , {nullptr                             , {}}},
		{"GAME.PlayAmbientTrack"                       , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.FadeInAmbientTrack"                     , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.FadeOutAmbientTrack"                    , {nullptr                             , {kFloat}}},
		{"GAME.StopAmbientTrack"                       , {nullptr                             , {}}},
		{"GAME.PlayTemporaryAmbientTrack"              , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.StopTemporaryAmbientTrack"              , {nullptr                             , {kFloat}}},
		{"GAME.HasPlayerShotDuringLevel"               , {nullptr                             , {}}},
		{"GAME.HasPlayerDiedDuringLevel"               , {nullptr                             , {}}},
		{"GAME.IsAutoPlaying"                          , {nullptr                             , {}}},
		{"GAME.EnableRenderShadows"                    , {nullptr                             , {}}},
		{"GAME.EnableGodrays"                          , {nullptr                             , {}}},
		{"GAME.GetTimeHours"                           , {nullptr                             , {}}},
		{"GAME.GetTimeMinutes"                         , {nullptr                             , {}}},
		{"GAME.SetReverbPreset"                        , {nullptr                             , {kEntity}}},
		{"GAME.SetSoundPreset"                         , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.RemoveSoundPreset"                      , {nullptr                             , {kFloat}}},
		{"GAME.SetSoundPresetWithTimer"                , {nullptr                             , {kEntity, kFloat, kFloat, kFloat}}},
		{"GAME.CancelSoundPreset"                      , {nullptr                             , {kEntity, kFloat}}},
		{"GAME.SetPitchMultiplier"                     , {nullptr                             , {kFloat}}},
		{"GAME.SetTimeMultiplier"                      , {nullptr                             , {kFloat, kFloat}}},
		{"GAME.SetTemporaryTimeMultiplier"             , {nullptr                             , {kFloat, kFloat, kFloat}}},
		{"GAME.BlockAIShooting"                        , {nullptr                             , {kFloat}}},
		{"GAME.EnableRumble"                           , {nullptr                             , {kBool, kFloat, kFloat}}},
		{"GAME.SetMaximumFPS"                          , {nullptr                             , {kInt}}},
		{"GAME.SetGravityScale"                        , {nullptr                             , {kFloat}}},
		{"GAME.EnableFlareCinematicMoment"             , {nullptr                             , {kBool}}},
		{"GAME.SetAmbiance"                            , {nullptr                             , {kString, kFloat}}},
		{"GAME.SetAmbianceWithTimer"                   , {nullptr                             , {kString, kFloat, kFloat, kFloat}}},
		{"GAME.PlayCinematicEffect"                    , {nullptr                             , {kFloat, kFloat, kFloat}}},
		{"GAME.SetShadowReferenceObject"               , {nullptr                             , {kEntity}}},
		{"GAME.ResetShadowReferenceObject"             , {nullptr                             , {}}},
		{"GAME.SetDarkLight"                           , {nullptr                             , {kFloat, kFloat, kFloat, kFloat}}},
		{"GAME.GetBoost"                               , {nullptr                             , {}}},
		{"GAME.TornadoStart"                           , {nullptr                             , {kEntity}}},
		{"GAME.TornadoStop"                            , {nullptr                             , {}}},
		{"GAME.PropBirdsEnable"                        , {nullptr                             , {kEntity}}},
		{"GAME.PropBirdsDisable"                       , {nullptr                             , {}}},
		{"GAME.ChestFound"                             , {nullptr                             , {kInt}}},
		{"GAME.UnlockAchievement"                      , {nullptr                             , {kInt}}},
		{"GAME.UnlockAvatarItem"                       , {nullptr                             , {kInt}}},
		{"GAME.UnlockGamerPic"                         , {nullptr                             , {kInt}}},
		{"GAME.GetActiveEnemyCount"                    , {nullptr                             , {}}},
		{"GAME.GetStoryModeRound"                      , {&Functions::getStoryModeRound       , {}}},
		{"GAME.StoryModeRoundCompleted"                , {nullptr                             , {}}},
		{"GAME.TrialGameCompleted"                     , {nullptr                             , {}}},
		{"GAME.GameCompleted"                          , {nullptr                             , {}}},
		{"GAME.ArcadeCompleted"                        , {nullptr                             , {}}},
		{"GAME.ArcadeIntro"                            , {nullptr                             , {}}},
		{"GAME.ArcadeStart"                            , {nullptr                             , {kFloat}}},
		{"GAME.Difficulty"                             , {nullptr                             , {kFloat}}},
		{"GAME.EnableStorm"                            , {nullptr                             , {kBool}}},
		{"GAME.SetStormRisingEffect"                   , {nullptr                             , {kFloat, kFloat}}},
		{"GAME.HideCell"                               , {nullptr                             , {kBool, kInt, kInt}}},
		{"GAME.HideCell128"                            , {nullptr                             , {kBool, kInt, kInt}}},
		{"GAME.GetGameMode"                            , {nullptr                             , {}}},
		{"GAME.IsTrial"                                , {&Functions::isTrial                 , {}}},
		{"GAME.IsTrialModeB"                           , {&Functions::isTrialModeB            , {}}},
		{"GAME.UnlockCollectible"                      , {nullptr                             , {kEntity, kInt}}},
		{"GAME.IsCollectibleUnlocked"                  , {nullptr                             , {kEntity, kInt}}},
		{"GAME.GetUnlockedCollectibleCount"            , {nullptr                             , {kEntity}}},
		{"GAME.UnlockRadioShow"                        , {nullptr                             , {kEntity}}},
		{"GAME.UnlockManuscriptPage"                   , {nullptr                             , {kEntity}}},
		{"GAME.IsManuscriptPageUnlocked"               , {&Functions::isManuscriptPageUnlocked, {kEntity}}},
		{"GAME.GetUnlockedManuscriptPageCount"         , {nullptr                             , {}}},
		{"GAME.KillAllEnemies"                         , {nullptr                             , {}}},
		{"GAME.SetupSpawnDistances"                    , {nullptr                             , {kFloat, kFloat, kFloat, kFloat, kFloat}}},
		{"GAME.HasPlayedArcade"                        , {nullptr                             , {}}},
		{"GAME.TrialModeDeviationStarts"               , {nullptr                             , {}}},

		{"CAMERA.AttachTo"                             , {nullptr                             , {kEntity, kFloat}}},
		{"CAMERA.Detach"                               , {nullptr                             , {kFloat}}},
		{"CAMERA.LookAt"                               , {nullptr                             , {kEntity, kFloat}}},
		{"CAMERA.LookAt2"                              , {nullptr                             , {kEntity, kFloat, kFloat, kFloat, kFloat}}},
		{"CAMERA.StopLooking"                          , {nullptr                             , {kFloat}}},
		{"CAMERA.AlignTo"                              , {nullptr                             , {kEntity, kFloat}}},
		{"CAMERA.AbortAlign"                           , {nullptr                             , {}}},
		{"CAMERA.Setup"                                , {nullptr                             , {kEntity}}},
		{"CAMERA.SetupWithoutBlend"                    , {nullptr                             , {kEntity}}},
		{"CAMERA.SetFOVMultiplier"                     , {nullptr                             , {kFloat, kFloat}}},
		{"CAMERA.Shake"                                , {nullptr                             , {kFloat, kFloat}}},
		{"CAMERA.HandShake"                            , {nullptr                             , {kFloat, kFloat, kFloat}}},
		{"CAMERA.PlayPath"                             , {nullptr                             , {kEntity, kEntity, kFloat, kFloat, kBool, kBool}}},
		{"CAMERA.LookAtCharacter"                      , {nullptr                             , {kEntity, kString, kFloat}}},
		{"CAMERA.AbortLooking"                         , {nullptr                             , {}}},
		{"CAMERA.AttachToPath"                         , {nullptr                             , {kEntity, kEntity, kEntity, kFloat}}},

		{"HUD.Print"                                   , {nullptr                             , {kString}}},
		{"HUD.PrintFloat"                              , {nullptr                             , {kFloat}}},
		{"HUD.PrintInt"                                , {nullptr                             , {kInt}}},
		{"HUD.PrintInfo"                               , {nullptr                             , {kString}}},
		{"HUD.FadeInHUD"                               , {nullptr                             , {}}},
		{"HUD.FadeOutHUD"                              , {nullptr                             , {}}},
		{"HUD.AddFlash"                                , {nullptr                             , {kString, kFloat, kFloat, kFloat}}},
		{"HUD.SetFade"                                 , {nullptr                             , {kString, kFloat}}},
		{"HUD.HideMap"                                 , {nullptr                             , {kBool}}},
		{"HUD.MapZoom"                                 , {nullptr                             , {kFloat}}},
		{"HUD.EnableActiveReloadHint"                  , {nullptr                             , {kBool}}},
		{"HUD.SetGoal"                                 , {nullptr                             , {kString, kBool}}},
		{"HUD.RemoveGoal"                              , {nullptr                             , {}}},
		{"HUD.ChangeDestinationEntity"                 , {nullptr                             , {kEntity}}},
		{"HUD.SetDestinationEntity"                    , {nullptr                             , {kEntity, kBool, kBool, kBool}}},
		{"HUD.RemoveDestinationEntity"                 , {nullptr                             , {}}},
		{"HUD.AddMapEntity"                            , {nullptr                             , {kEntity, kString, kInt, kBool, kBool}}},
		{"HUD.AddMapEntity2"                           , {nullptr                             , {kEntity, kString, kInt, kBool, kBool, kBool, kBool}}},
		{"HUD.RemoveMapEntity"                         , {nullptr                             , {kEntity}}},
		{"HUD.ShowTimedCinematicPlaceholderText"       , {nullptr                             , {kString, kFloat}}},
		{"HUD.DrawProtoBar"                            , {nullptr                             , {kBool}}},
		{"HUD.SetProtoBarFillRate"                     , {nullptr                             , {kFloat}}},
		{"HUD.ShowIcon"                                , {nullptr                             , {kInt, kInt, kInt}}},
		{"HUD.HideIcon"                                , {nullptr                             , {kInt}}},

		{"LockDoor"                                    , {nullptr                             , {kBool}}},
		{"Hide"                                        , {&Functions::hide                    , {kEntity}}},
		{"Animate"                                     , {&Functions::animate                 , {}}},
		{"StartTimer"                                  , {&Functions::startTimer              , {kInt, kFloat, kInt}}},
		{"StartTimerWithDuration"                      , {&Functions::startTimerWithDuration  , {kInt, kFloat, kInt, kFloat}}},
		{"EnablePointLight"                            , {&Functions::enablePointLight        , {kBool}}},
		{"EnableTrigger"                               , {nullptr                             , {kBool}}}
};

}

